# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: managers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='managers.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emanagers.proto\"\x0f\n\rEmptyMesssage\"%\n\x13ManagerPingResponse\x12\x0e\n\x06Result\x18\x01 \x01(\t\"#\n\x0eManagerRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\"\xa8\x01\n\x0fManagerResponse\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0f\n\x07year_id\x18\x02 \x01(\t\x12\x0f\n\x07team_id\x18\x03 \x01(\t\x12\r\n\x05lg_id\x18\x04 \x01(\t\x12\x10\n\x08inseason\x18\x05 \x01(\t\x12\t\n\x01G\x18\x06 \x01(\t\x12\t\n\x01W\x18\x07 \x01(\t\x12\t\n\x01L\x18\x08 \x01(\t\x12\x0c\n\x04rank\x18\t \x01(\t\x12\x10\n\x08plyr_mgr\x18\n \x01(\t2q\n\x07Manager\x12\x34\n\x0cPingManagers\x12\x0e.EmptyMesssage\x1a\x14.ManagerPingResponse\x12\x30\n\x0bGetManagers\x12\x0f.ManagerRequest\x1a\x10.ManagerResponseb\x06proto3'
)




_EMPTYMESSSAGE = _descriptor.Descriptor(
  name='EmptyMesssage',
  full_name='EmptyMesssage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=33,
)


_MANAGERPINGRESPONSE = _descriptor.Descriptor(
  name='ManagerPingResponse',
  full_name='ManagerPingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Result', full_name='ManagerPingResponse.Result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=72,
)


_MANAGERREQUEST = _descriptor.Descriptor(
  name='ManagerRequest',
  full_name='ManagerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='ManagerRequest.player_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=109,
)


_MANAGERRESPONSE = _descriptor.Descriptor(
  name='ManagerResponse',
  full_name='ManagerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='ManagerResponse.player_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='year_id', full_name='ManagerResponse.year_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='team_id', full_name='ManagerResponse.team_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lg_id', full_name='ManagerResponse.lg_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inseason', full_name='ManagerResponse.inseason', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='G', full_name='ManagerResponse.G', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='W', full_name='ManagerResponse.W', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='L', full_name='ManagerResponse.L', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rank', full_name='ManagerResponse.rank', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='plyr_mgr', full_name='ManagerResponse.plyr_mgr', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=280,
)

DESCRIPTOR.message_types_by_name['EmptyMesssage'] = _EMPTYMESSSAGE
DESCRIPTOR.message_types_by_name['ManagerPingResponse'] = _MANAGERPINGRESPONSE
DESCRIPTOR.message_types_by_name['ManagerRequest'] = _MANAGERREQUEST
DESCRIPTOR.message_types_by_name['ManagerResponse'] = _MANAGERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMesssage = _reflection.GeneratedProtocolMessageType('EmptyMesssage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSSAGE,
  '__module__' : 'managers_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMesssage)
  })
_sym_db.RegisterMessage(EmptyMesssage)

ManagerPingResponse = _reflection.GeneratedProtocolMessageType('ManagerPingResponse', (_message.Message,), {
  'DESCRIPTOR' : _MANAGERPINGRESPONSE,
  '__module__' : 'managers_pb2'
  # @@protoc_insertion_point(class_scope:ManagerPingResponse)
  })
_sym_db.RegisterMessage(ManagerPingResponse)

ManagerRequest = _reflection.GeneratedProtocolMessageType('ManagerRequest', (_message.Message,), {
  'DESCRIPTOR' : _MANAGERREQUEST,
  '__module__' : 'managers_pb2'
  # @@protoc_insertion_point(class_scope:ManagerRequest)
  })
_sym_db.RegisterMessage(ManagerRequest)

ManagerResponse = _reflection.GeneratedProtocolMessageType('ManagerResponse', (_message.Message,), {
  'DESCRIPTOR' : _MANAGERRESPONSE,
  '__module__' : 'managers_pb2'
  # @@protoc_insertion_point(class_scope:ManagerResponse)
  })
_sym_db.RegisterMessage(ManagerResponse)



_MANAGER = _descriptor.ServiceDescriptor(
  name='Manager',
  full_name='Manager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=282,
  serialized_end=395,
  methods=[
  _descriptor.MethodDescriptor(
    name='PingManagers',
    full_name='Manager.PingManagers',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSSAGE,
    output_type=_MANAGERPINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetManagers',
    full_name='Manager.GetManagers',
    index=1,
    containing_service=None,
    input_type=_MANAGERREQUEST,
    output_type=_MANAGERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MANAGER)

DESCRIPTOR.services_by_name['Manager'] = _MANAGER

# @@protoc_insertion_point(module_scope)
