# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import managers_pb2 as managers__pb2


class ManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingManagers = channel.unary_unary(
                '/Manager/PingManagers',
                request_serializer=managers__pb2.EmptyMesssage.SerializeToString,
                response_deserializer=managers__pb2.ManagerPingResponse.FromString,
                )
        self.GetManagers = channel.unary_unary(
                '/Manager/GetManagers',
                request_serializer=managers__pb2.ManagerRequest.SerializeToString,
                response_deserializer=managers__pb2.ManagerResponse.FromString,
                )


class ManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingManagers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManagers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingManagers': grpc.unary_unary_rpc_method_handler(
                    servicer.PingManagers,
                    request_deserializer=managers__pb2.EmptyMesssage.FromString,
                    response_serializer=managers__pb2.ManagerPingResponse.SerializeToString,
            ),
            'GetManagers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManagers,
                    request_deserializer=managers__pb2.ManagerRequest.FromString,
                    response_serializer=managers__pb2.ManagerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Manager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Manager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingManagers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Manager/PingManagers',
            managers__pb2.EmptyMesssage.SerializeToString,
            managers__pb2.ManagerPingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetManagers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Manager/GetManagers',
            managers__pb2.ManagerRequest.SerializeToString,
            managers__pb2.ManagerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
