# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sales_record.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sales_record.proto\"\x0f\n\rEmptyMesssage\")\n\x17SalesRecordPingResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"#\n\x13SalesRecordResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"!\n\x0ePayloadRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x82\x01\n\x12SalesRecordRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x11\n\titem_type\x18\x02 \x01(\t\x12\x12\n\nunits_sold\x18\x03 \x01(\t\x12\x12\n\nunit_price\x18\x04 \x01(\t\x12\x11\n\tunit_cost\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t2\x8c\x02\n\x0bSalesRecord\x12<\n\x10PingSalesRecords\x12\x0e.EmptyMesssage\x1a\x18.SalesRecordPingResponse\x12=\n\x10SendSalesRecords\x12\x13.SalesRecordRequest\x1a\x14.SalesRecordResponse\x12\x39\n\x10SendSalesPayload\x12\x0f.PayloadRequest\x1a\x14.SalesRecordResponse\x12\x45\n\x16SendSalesRecordsStream\x12\x13.SalesRecordRequest\x1a\x14.SalesRecordResponse(\x01\x62\x06proto3')



_EMPTYMESSSAGE = DESCRIPTOR.message_types_by_name['EmptyMesssage']
_SALESRECORDPINGRESPONSE = DESCRIPTOR.message_types_by_name['SalesRecordPingResponse']
_SALESRECORDRESPONSE = DESCRIPTOR.message_types_by_name['SalesRecordResponse']
_PAYLOADREQUEST = DESCRIPTOR.message_types_by_name['PayloadRequest']
_SALESRECORDREQUEST = DESCRIPTOR.message_types_by_name['SalesRecordRequest']
EmptyMesssage = _reflection.GeneratedProtocolMessageType('EmptyMesssage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSSAGE,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMesssage)
  })
_sym_db.RegisterMessage(EmptyMesssage)

SalesRecordPingResponse = _reflection.GeneratedProtocolMessageType('SalesRecordPingResponse', (_message.Message,), {
  'DESCRIPTOR' : _SALESRECORDPINGRESPONSE,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:SalesRecordPingResponse)
  })
_sym_db.RegisterMessage(SalesRecordPingResponse)

SalesRecordResponse = _reflection.GeneratedProtocolMessageType('SalesRecordResponse', (_message.Message,), {
  'DESCRIPTOR' : _SALESRECORDRESPONSE,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:SalesRecordResponse)
  })
_sym_db.RegisterMessage(SalesRecordResponse)

PayloadRequest = _reflection.GeneratedProtocolMessageType('PayloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _PAYLOADREQUEST,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:PayloadRequest)
  })
_sym_db.RegisterMessage(PayloadRequest)

SalesRecordRequest = _reflection.GeneratedProtocolMessageType('SalesRecordRequest', (_message.Message,), {
  'DESCRIPTOR' : _SALESRECORDREQUEST,
  '__module__' : 'sales_record_pb2'
  # @@protoc_insertion_point(class_scope:SalesRecordRequest)
  })
_sym_db.RegisterMessage(SalesRecordRequest)

_SALESRECORD = DESCRIPTOR.services_by_name['SalesRecord']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSSAGE._serialized_start=22
  _EMPTYMESSSAGE._serialized_end=37
  _SALESRECORDPINGRESPONSE._serialized_start=39
  _SALESRECORDPINGRESPONSE._serialized_end=80
  _SALESRECORDRESPONSE._serialized_start=82
  _SALESRECORDRESPONSE._serialized_end=117
  _PAYLOADREQUEST._serialized_start=119
  _PAYLOADREQUEST._serialized_end=152
  _SALESRECORDREQUEST._serialized_start=155
  _SALESRECORDREQUEST._serialized_end=285
  _SALESRECORD._serialized_start=288
  _SALESRECORD._serialized_end=556
# @@protoc_insertion_point(module_scope)
